name: Task
description: Nový úkol nebo feature
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Popis
      description: Co je třeba udělat?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Jak poznáme, že je to hotovo?
      value: |
        - [ ]
